- name: deploy CD
  hosts:   
    - 192.168.5.134
      
  #gather_facts: yes
  #remote_user: slave
  vars:
      recursion: yes
      servers:
              - { hostname: slave, ip: 192.168.5.132 }
      ansible_python_interpreter: "{{ ansible_playbook_python }}"    
  #become: yes

  tasks:
      - name: Install git
        yum:
          name: git
          state: present
          update_cache: yes

      - name: Install httpd
        yum:
          name: httpd
          state: present

      - name: install Java
        yum:
          name: java-1.8.0-openjdk-devel
          state: present
          update_cache: yes

      - name : "git clone"
        git:
          repo: https://github.com/AyedHaithem1/cd.git
          dest: /home/slave/cicd-training/
          version: master
          force: yes
#      - name: Run a command that uses non-posix shell-isms (in this example /bin/sh doesn't handle redirection and wildcards together but bash does)
#        shell: cd 
#        args:
#          executable: /bin/bash
      

      - name: Copy file to perform the clean
        #template: src=/root/cicd-training/deploy.sh dest=/home/slave/cicd-training/
        ansible.builtin.shell:
          cmd: chmod 777 deploy.sh;
          chdir: /home/slave/cicd-training
          warn: False
      - name: MVN clean package and build
        ansible.builtin.shell:
        #become: root
          #update_cache: yes  
          cmd: mvn clean package docker:build -DskipTests 
          chdir: "/home/slave/cicd-training/demo-rest-api"
          warn: False
      - name: MVN clean package and build
        ansible.builtin.shell:
          cmd: docker-compose up -d
          chdir: "/home/slave/cicd-training/"
          warn: False


 
  handlers:
   #- name: restart apache2
   #   service: name=apache2 state=restarted
   
